"""initial schema

Revision ID: 0a9fc379d832
Revises: 
Create Date: 2026-07-30 17:38:31.842946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a9fc379d832'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_type',
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('category', 'subcategory')
    )
    op.create_table('entity',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['category', 'subcategory'], ['entity_type.category', 'entity_type.subcategory'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'subcategory', 'name', name='uq_entity_name_per_subcategory')
    )
    op.create_index('idx_entity_attributes_gin', 'entity', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_entity_correlation_id'), 'entity', ['correlation_id'], unique=False)
    op.create_table('entity_status',
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category', 'subcategory'], ['entity_type.category', 'entity_type.subcategory'], ),
    sa.PrimaryKeyConstraint('category', 'subcategory', 'status')
    )
    op.create_table('entity_relationship',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parent_entity_id', sa.UUID(), nullable=False),
    sa.Column('child_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['child_entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_entity_id', 'child_entity_id', 'relationship_type')
    )
    op.create_index(op.f('ix_entity_relationship_child_entity_id'), 'entity_relationship', ['child_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationship_parent_entity_id'), 'entity_relationship', ['parent_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationship_relationship_type'), 'entity_relationship', ['relationship_type'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('causation_type', sa.String(), nullable=True),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('producer_version', sa.String(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_events_causation', 'events', ['causation_type', 'causation_id'], unique=False)
    op.create_index('idx_events_correlation_id', 'events', ['correlation_id'], unique=False)
    op.create_index('idx_events_entity', 'events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_events_type_occurred', 'events', ['event_type', 'occurred_at'], unique=False)
    op.create_index('idx_events_unpublished', 'events', ['published_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('event_handler_checkpoints',
    sa.Column('handler_name', sa.String(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('handler_name', 'event_id')
    )
    op.create_table('event_handler_failures',
    sa.Column('handler_name', sa.String(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('first_failed_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('handler_name', 'event_id')
    )
    op.create_index(op.f('ix_event_handler_failures_next_attempt_at'), 'event_handler_failures', ['next_attempt_at'], unique=False)
    # ### end Alembic commands ###

    # Hand-written: autogenerate compares tables, columns, indexes and
    # constraints, and is blind to functions and triggers. A plain CHECK
    # cannot validate a column against another table, so each subcategory's
    # state machine is enforced here instead, against entity_status.
    #
    # The single %s below are literal -- unlike the copy in
    # entitymodel/models.py, which must double them because SQLAlchemy's DDL
    # construct runs printf interpolation over its string. op.execute does
    # not, so doubling them here would emit %% into the function body.
    op.execute("""
        CREATE OR REPLACE FUNCTION validate_entity_status() RETURNS TRIGGER AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM entity_status
                WHERE category = NEW.category
                  AND subcategory = NEW.subcategory
                  AND status = NEW.status
            ) THEN
                RAISE EXCEPTION 'invalid status % for %/%',
                    NEW.status, NEW.category, NEW.subcategory;
            END IF;
            -- clock_timestamp(), not now(): now() is transaction start time,
            -- so two updates to one row in a single transaction would leave
            -- updated_at unchanged.
            NEW.updated_at := clock_timestamp();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_validate_entity_status
        BEFORE INSERT OR UPDATE ON entity
        FOR EACH ROW EXECUTE FUNCTION validate_entity_status();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the trigger before its table. The function is dropped separately:
    # DROP TABLE removes the trigger but leaves the function behind.
    op.execute("DROP TRIGGER IF EXISTS trg_validate_entity_status ON entity")
    op.execute("DROP FUNCTION IF EXISTS validate_entity_status()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_handler_failures_next_attempt_at'), table_name='event_handler_failures')
    op.drop_table('event_handler_failures')
    op.drop_table('event_handler_checkpoints')
    op.drop_index('idx_events_unpublished', table_name='events', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_index('idx_events_type_occurred', table_name='events')
    op.drop_index('idx_events_entity', table_name='events')
    op.drop_index('idx_events_correlation_id', table_name='events')
    op.drop_index('idx_events_causation', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_entity_relationship_relationship_type'), table_name='entity_relationship')
    op.drop_index(op.f('ix_entity_relationship_parent_entity_id'), table_name='entity_relationship')
    op.drop_index(op.f('ix_entity_relationship_child_entity_id'), table_name='entity_relationship')
    op.drop_table('entity_relationship')
    op.drop_table('entity_status')
    op.drop_index(op.f('ix_entity_correlation_id'), table_name='entity')
    op.drop_index('idx_entity_attributes_gin', table_name='entity', postgresql_using='gin')
    op.drop_table('entity')
    op.drop_table('entity_type')
    # ### end Alembic commands ###
