"""add cancelled_reason to checkpoints

Revision ID: 5a072b1fb587
Revises: 0a9fc379d832
Create Date: 2026-08-11 15:01:24.149497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a072b1fb587'
down_revision: Union[str, Sequence[str], None] = '0a9fc379d832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nullable, and deliberately not backfilled: NULL means "the handler did
    # the work", which is true of every checkpoint written before this column
    # existed. There was no way to decline an event then.
    op.add_column('event_handler_checkpoints', sa.Column('cancelled_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_handler_checkpoints', 'cancelled_reason')
    # ### end Alembic commands ###
